name: CI

on:
  push:
    branches: [ main ]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testing
    runs-on: 'ubuntu-latest'
    steps:
    - name: Get source
      uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
